import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 20,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 32,
  },
  errorTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#f97316',
    marginTop: 16,
    marginBottom: 8,
    textAlign: 'center',
  },
  errorMessage: {
    fontSize: 16,
    color: '#9e6b47',
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 24,
  },
  backButton: {
    backgroundColor: '#f97316',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  backButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  entityInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    padding: 16,
    borderRadius: 8,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#f4ece6',
  },
  entityDetails: {
    marginLeft: 12,
    flex: 1,
  },
  entityType: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1c130d',
  },
  entityId: {
    fontSize: 14,
    color: '#81736a',
    marginTop: 2,
  },
  conflictField: {
    fontSize: 14,
    color: '#f97316',
    marginTop: 2,
  },
  comparisonContainer: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1c130d',
    marginBottom: 16,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    padding: 12,
    marginBottom: 2,
    borderWidth: 1,
    borderColor: '#e9ecef',
  },
  tableHeaderText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: '#495057',
    textAlign: 'center',
  },
  tableRow: {
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e9ecef',
    alignItems: 'center',
  },
  conflictRow: {
    backgroundColor: '#fef2f2',
    borderBottomColor: '#fecaca',
  },
  fieldCell: {
    flex: 1,
    fontSize: 14,
    fontWeight: '500',
    color: '#374151',
    textAlign: 'left',
    paddingRight: 8,
  },
  dataCell: {
    flex: 1,
    fontSize: 14,
    color: '#374151',
    textAlign: 'center',
    paddingHorizontal: 4,
  },
  conflictText: {
    color: '#f97316',
    fontWeight: '600',
  },
  resolutionContainer: {
    marginBottom: 24,
  },
  resolutionOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f4f2f1',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#6b7280',
  },
  selectedOption: {
    backgroundColor: '#ffffff',
    borderColor: '#f97316',
  },
  optionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1c130d',
    marginLeft: 12,
  },
  selectedOptionTitle: {
    color: '#f97316',
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 20,
    marginBottom: 40,
    paddingHorizontal: 0,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: '#f4f2f1',
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#6b7280',
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#6b7280',
  },
  confirmButton: {
    flex: 1,
    backgroundColor: '#f97316',
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  disabledButton: {
    backgroundColor: '#9ca3af',
  },
  confirmButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ffffff',
  },
  uniqueConstraintText: {
    fontSize: 16,
    color: '#f97316',
    fontWeight: '600',
    marginBottom: 16,
    textAlign: 'center',
  },
  editableContainer: {
    backgroundColor: '#ffffff',
    padding: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#f4ece6',
    marginBottom: 12,
  },
  editableLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1c130d',
    marginBottom: 8,
  },
  editableInput: {
    backgroundColor: '#f9fafb',
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 16,
    color: '#374151',
  },
  noOptionsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#f9fafb',
    borderRadius: 8,
    marginVertical: 8,
  },
  noOptionsText: {
    marginLeft: 8,
    fontSize: 16,
    color: '#6b7280',
    flex: 1,
  },
  strategyInfoContainer: {
    backgroundColor: '#eff6ff',
    borderWidth: 1,
    borderColor: '#bfdbfe',
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
  },
  strategyInfoText: {
    fontSize: 14,
    color: '#1e40af',
    fontWeight: '500',
  },
  warningContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#fef3c7',
    borderWidth: 1,
    borderColor: '#f59e0b',
    borderRadius: 8,
    padding: 12,
    marginTop: 16,
  },
  warningText: {
    marginLeft: 8,
    fontSize: 14,
    color: '#92400e',
    flex: 1,
    lineHeight: 20,
  },
});
